-- This module is generated by `setem` command. DO NOT edit manually!


module RecordSetter exposing (..)


s_attack : a -> { b | attack : a } -> { b | attack : a }
s_attack value__ record__ =
    { record__ | attack = value__ }


s_body : a -> { b | body : a } -> { b | body : a }
s_body value__ record__ =
    { record__ | body = value__ }


s_cards : a -> { b | cards : a } -> { b | cards : a }
s_cards value__ record__ =
    { record__ | cards = value__ }


s_draw : a -> { b | draw : a } -> { b | draw : a }
s_draw value__ record__ =
    { record__ | draw = value__ }


s_guard : a -> { b | guard : a } -> { b | guard : a }
s_guard value__ record__ =
    { record__ | guard = value__ }


s_history : a -> { b | history : a } -> { b | history : a }
s_history value__ record__ =
    { record__ | history = value__ }


s_init : a -> { b | init : a } -> { b | init : a }
s_init value__ record__ =
    { record__ | init = value__ }


s_mana : a -> { b | mana : a } -> { b | mana : a }
s_mana value__ record__ =
    { record__ | mana = value__ }


s_name : a -> { b | name : a } -> { b | name : a }
s_name value__ record__ =
    { record__ | name = value__ }


s_subscriptions : a -> { b | subscriptions : a } -> { b | subscriptions : a }
s_subscriptions value__ record__ =
    { record__ | subscriptions = value__ }


s_title : a -> { b | title : a } -> { b | title : a }
s_title value__ record__ =
    { record__ | title = value__ }


s_update : a -> { b | update : a } -> { b | update : a }
s_update value__ record__ =
    { record__ | update = value__ }


s_value : a -> { b | value : a } -> { b | value : a }
s_value value__ record__ =
    { record__ | value = value__ }


s_view : a -> { b | view : a } -> { b | view : a }
s_view value__ record__ =
    { record__ | view = value__ }


s_vulnerable : a -> { b | vulnerable : a } -> { b | vulnerable : a }
s_vulnerable value__ record__ =
    { record__ | vulnerable = value__ }
